### ISSUE TITLE
Should options.safe (bool) be set to true by default?

### ISSUE THREAD

**Issue by JonoB** [ben-eb/gulp-cssnano#10]
cssnano includes (by default) a few optimisations that are not safe.

> options.safe (bool)

> Set this to true to disable advanced optimisations that are not always safe. Currently, this disables custom identifier reduction, z-index rebasing, unused at-rule removal & conversion between absolute length values.

Consider setting this to true by default, or at least putting a big fat warning on github readme please :)

**Comment by ben-eb** [comment]
> [W]e should [...] look to making v4 run safe by default. Transforms such as postcss-zindex are not intuitive default options - we assume too much from a user by turning it on by default. So in v4, we will expose a core module that is safe by default, and then presets for cssnano's more aggressive behaviours.

https://github.com/ben-eb/cssnano/issues/88

**Comment by JonoB** [comment]
OK cool.

I just lost half a day to my z-indexes getting all changed :)

Can you please put a warning on the front page of the readme in the meantime?

**Comment by ben-eb** [comment]
Done. https://github.com/ben-eb/cssnano/commit/cbd2f97373fd8c8d153bce1b82341b885f0ea792

**Comment by JonoB** [comment]
Thank you kindly!
