### ISSUE TITLE
all z-index properties are 1

### ISSUE THREAD

**Issue by alexeyzernov** [ben-eb/gulp-cssnano#14]
I've got div with "header" class 
`.header { //some code; z-index:100; }`
and image with
`.profile-top-img
{
//some code;
z-index: 1;
`}

After minification with cssnano `.header` has `z-index:1`, other minificators did it with right value (100).

**Comment by ben-eb** [comment]
Yep, it's a feature which we plan to disable by default for v4. https://github.com/ben-eb/cssnano/issues/88

https://github.com/ben-eb/postcss-zindex

**Comment by cm325** [comment]
Yeah, given that the values that were generated were incorrect for my app, this really ought to be an optional, non-default feature
