### ISSUE TITLE
gulp-cssnano BUG

### ISSUE THREAD

**Issue by semiromid** [ben-eb/gulp-cssnano#15]
Hi! See you bug in gulp-cssnano:

if writed

.border_radius {
  -webkit-border-radius: 8px;
  border-radius: 8px; }

Not will in minify file  -  -webkit-border-radius: 8px;
gulp-cssnano will remove   -webkit-border-radius: 8px;

if write

.border_radius {
  border-radius: 8px; 
-webkit-border-radius: 8px;}

gulp-cssnano will not remove   -webkit-border-radius: 8px;

**Comment by ben-eb** [comment]
It's not a bug; cssnano uses autoprefixer to remove prefixes that are no longer necessary. `-webkit-border-radius` is not used by modern browsers. If you need to support these prefixes you can pass the browsers that you would like to support with the options object.

```
{
  autoprefixer: {browsers: 'last 2 versions'}
}
```

See https://github.com/ai/browserslist for the available options.
