### ISSUE TITLE
z-index being modified, creating style issues

### ISSUE THREAD

**Issue by leemcd56** [ben-eb/gulp-cssnano#18]
I moved from using `gulp-minify-css` to `gulp-cssnano` in my project folder and I am having an issue with all instances of `z-index` being reduced to single-digits (i.e., **100** reduced to **7**, **50** reduced to **6**). This would be acceptable in most cases, but we have many high indexes in our sitewide CSS that conflicts with this and causes UI problems. Is there a way to disable this?

**Comment by ben-eb** [comment]
https://github.com/ben-eb/gulp-cssnano/issues/14
