### ISSUE TITLE
gulp-cssnano is too slow

### ISSUE THREAD

**Issue by techhysahil** [ben-eb/gulp-cssnano#24]
I was thinking of moving from Grunt to gulp but here is the problem. All the time other gulp task is saving is taken by any gulp minify task. Below i am attaching the results.
![screen shot 2016-01-26 at 3 29 09 pm](https://cloud.githubusercontent.com/assets/7847056/12577638/92feb72e-c441-11e5-81e4-3eb43e3bd4f5.png)

As shown in above screenshot. i am minify 8 css files both using Grunt as well as gulp. Time difference is quite noticeable to me:

Gulp : 3.47s
Grunt : 90 ms

This is way worse than the result for  gulp-minify-css & gulp-cssmin. Time taken by these 2 are aprox:
gulp-minify-css : 827 ms
gulp-cssmin : 700 ms

Also posting my gulp file here...

var gulp = require('gulp'),
    uglify = require('gulp-uglify'),
    sass = require('gulp-sass'),
    watch = require('gulp-watch'),
    cssnano = require('gulp-cssnano'),
    concat = require('gulp-concat'),
    minifyCss = require('gulp-minify-css'),
    cssmin = require('gulp-cssmin');

gulp.task('sass', function () {
    gulp.src('./src/scss/main.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(gulp.dest('./dist/style/gulp.css'));
});

gulp.task('cssmin', function() {
    return gulp.src(['src/external/components/webmodules-bootstrap/css/bootstrap.min.css',
        'src/external/components/jqmodules-x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css',
        'src/external/components/jqtags-jq-date/jqtags.date.css',
        'src/external/components/webmodules-jqtag/jqtag.css',
        'src/external/components/jqmodules-bootstrap-select/dist/css/bootstrap-select.min.css',
        'src/external/components/jqmodules-select2/select2.css',
        'src/external/components/bootstrap-material-design/dist/css/bootstrap-material-design.min.css',
        'src/external/components/bootstrap-material-design/dist/css/ripples.min.css'
    ])
    .pipe(cssnano())
    .pipe(gulp.dest('./dist/check'));
});

gulp.task('watch', function() {
    gulp.watch('src/modules/**/*.scss', ['sass']);
});

I want to know, Is there anything i am doing wrong or this is how it is?
Also let me know if gulp have any faster plugin for minification.

**Comment by ben-eb** [comment]
Performance is being addressed in version 4. We do a lot of optimisations but the way that they are done means that extra time is taken, so we need a better architecture. This is discussed in the v4 roadmap issue.

* v4 roadmap: https://github.com/ben-eb/cssnano/issues/88
* Duplicate issue: https://github.com/ben-eb/cssnano/issues/47

This is a known issue so I'm closing this in favour of the two issues above.

**Comment by techhysahil** [comment]
Thanks fr the quick reply.
