### ISSUE TITLE
cssnano breaks Dropzone

### ISSUE THREAD

**Issue by wuethrich44** [ben-eb/gulp-cssnano#25]
When I minify css with cssnano my upload form which is made with Dropzone is broken. With gulp-minify-css the upload form isn't broken. I also tried to enable safe mode like this:

```javascript
.pipe(minifyCss({safe: true}))
```

Broken upload form:

![image](https://cloud.githubusercontent.com/assets/6050639/12580096/0821655c-c42d-11e5-9a91-f3c59aa3c8d7.png)

Correct upload form:

![image](https://cloud.githubusercontent.com/assets/6050639/12580175/a29e11f2-c42d-11e5-9f06-6054f6f89f41.png)

I know it is difficult to track down this error but does anybody have a idea which is the cause for this error?

**Comment by ben-eb** [comment]
Can you try with `{mergeRules: false}`?

**Comment by wuethrich44** [comment]
Thanks for your fast reply but your approach doesn't work

**Comment by ben-eb** [comment]
Would you be able to provide an example so that I can reproduce the error?

**Comment by wuethrich44** [comment]
I dig deeper into that problem and it turns out that I '@import' a css file in a Sass file. Sass doesn't import the css file instead it create a `@import` with a wrong path. So I close this issue and thank you for your help anyway.

**Comment by ben-eb** [comment]
Ah okay, thanks for the update. :+1:
