### ISSUE TITLE
cssnano breaks task when using liquid css

### ISSUE THREAD

**Issue by goldsteinr** [ben-eb/gulp-cssnano#26]
I'm using shopify, so my scss is full of liquid statements. Is there a way to minify scss.liquid with cssnano?

```
[14:47:12] Using gulpfile ~\gulpfile.js
[14:47:12] Starting 'scss'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: all.scss:1832:30: Unknown word
.divider {
    border-top: 1px solid {{ settings.color-border }};
                              ^
}
```

**Comment by ai** [comment]
Very crazy task, but there is few possible solutions:

1. You can write custom parser for PostCSS. here is big docs about writing parsers: https://github.com/postcss/postcss/blob/master/docs/syntax.md
2. You can create some hack filters. Replace `{{` to `[[` before PostCSS and then `]]` to `}}` after PostCSS.

**Comment by ben-eb** [comment]
Closing for https://github.com/ben-eb/cssnano/issues/110.
