### ISSUE TITLE
Include options in docs

### ISSUE THREAD

**Issue by pettyron** [ben-eb/gulp-cssnano#32]
It took me forever to figure out that cssnano was messing with my z-indexing. It would have been handy to know from the npm docs that I could just set { zindex: false } as an option. It would be really cool to know what other options are available as well.

Thank you

**Comment by ben-eb** [comment]
Does http://cssnano.co/options/ work for you? Documentation is surely an area where we can improve though. :smile:

**Comment by pettyron** [comment]
Yes it is perfect. How this did not turn up in my searches, I do not know.

Thank you

Sent from my iPhone

On Feb 4, 2016, at 3:35 PM, Ben Briggs <notifications@github.com<mailto:notifications@github.com>> wrote:


Does http://cssnano.co/options/ work for you? Documentation is surely an area where we can improve though. [:smile:]

-

**Comment by ben-eb** [comment]
Alright, great! :smile:

**Comment by guilhermeocosta** [comment]
This URL seems to be missing 😭 

[http://cssnano.co/options/](http://cssnano.co/options/)

Where can i found the options docs now? Thanks!
