### ISSUE TITLE
problem in handling of !important in combination with a string value starting with a number and separated by a minus character (-)

### ISSUE THREAD

**Issue by franktopel** [ben-eb/gulp-cssnano#37]
We have been using gulp-minify-css up until today. We now switched to cssnano and suddenly all the icons on our web site were broken.

We use an icon font whose name we put in a variable in SCSS:

`$icon-font-name:        "11880-icons";`

All our icons use

`font-family: $icon-font-name !important;`

to make sure browser extensions never overwrite our icons with their own fonts.

The generated CSS from **gulp-minify-css** looks like this:

`font-family:'11880-icons'!important;`

and it works.

For the same SCSS, the generated CSS by **cssnano** is this:

`font-family:11880-icons!important;`

which makes Chrome say "illegal property value" for font-family in the browser.

**Comment by ben-eb** [comment]
Try reinstalling postcss-minify-font-values, we just pushed out a fix. :smile:

**Comment by franktopel** [comment]
Thank you for your extremely fast reaction. Works!

**Comment by ben-eb** [comment]
Awesome! :+1:
