### ISSUE TITLE
Poor optimizations results

### ISSUE THREAD

**Issue by fnocke** [ben-eb/gulp-cssnano#39]
`gulp-minify-css` [says its deprecated](https://www.npmjs.com/package/gulp-minify-css), and points to [gulp-css-nano](https://github.com/ben-eb/gulp-cssnano) as its successor.

Hoever, why does gulp-css-nano (2.1.1) give me so much weaker results?
I sought for help with a very short, isolated „testcase“ on stackoverflow:

http://stackoverflow.com/questions/35574050/why-is-css-nano-so-much-weaker-than-deprecated-minify-css

Is this 'early stage' on some common things? Nano modules that need to be explicitly enabled?
Or a bug in the gulp-wrapper? (I am wildly guessing. sorry.)

![side-by-side](https://cloud.githubusercontent.com/assets/16503718/13247864/e8f1221c-da1b-11e5-87e0-ea9fd8b9fac9.png)

**Comment by ben-eb** [comment]
All minifiers have different levels of support for different optimisations, so output will vary depending on which engine you use and what styles you have. In this specific case, clean-css does rule restructuring to merge duplicated selectors, something that I want to look into but haven't had the chance yet.

Of course, you are free to use clean-css instead if you find it produces a better output.

https://www.npmjs.com/package/gulp-clean-css

**Comment by fnocke** [comment]
Thank you for your answer!
(I was honestly wondering, if I got something wrong. No criticism disguised as a bug.)
