### ISSUE TITLE
Docs on how to pass options in?

### ISSUE THREAD

**Issue by benfrain** [ben-eb/gulp-cssnano#4]
For those new to this (read: me) is it worth indicated how to pass options in to the Gulp version of cssnano?

For example, is this the preferred way?:

```
.pipe(nano(
            options: {
                zindex: false
            }
        ))
```

Or should an object be made with the options inside and passed to the nano function?

Think it's fine to link to the options docs elsewhere but how to pass them in to the Gulp job would be good here ??

**Comment by ben-eb** [comment]
The same as any gulp task really:

```js
.pipe(nano({
  zindex: false
}))
```

**Comment by benfrain** [comment]
Yes, dunno what I was doing wrong. That was the first thing I tried and it wasn't working. Assumed this had some different funk going on. Clearly an error between keyboard and chair!

**Comment by ben-eb** [comment]
:smile:
