### ISSUE TITLE
z-index value is not getting reflected correctly

### ISSUE THREAD

**Issue by yasar88** [ben-eb/gulp-cssnano#41]
My scss partial file & sass compiled file having z-index:999; but the minified file is having the value of "z-index:25".
If i change the z-index:101, it is reflected as z-index:14; 
Am using gulp-cssnano 2.1.1 and gulp-sass 2.2.0

**Comment by ben-eb** [comment]
Duplicate of https://github.com/ben-eb/gulp-cssnano/issues/14.
