### ISSUE TITLE
colors replacing

### ISSUE THREAD

**Issue by librisius** [ben-eb/gulp-cssnano#42]
There one more problem, I'm working with ie9 and I need to have background-color: rgba(0, 0, 0, 0); not transparent, just rgba(0, 0, 0, 0), it's very important because in IE less than 10 click doesn't work on padding area if a block doesn't have any background!

I can fix this IE bug with rgba(0, 0, 0, 0), but cssnano compile it to transparent
Please fix it =)

**Comment by librisius** [comment]
colormin option has helped me

**Comment by ben-eb** [comment]
Seems like clean-css have had this problem too. https://github.com/jakubpawlowicz/clean-css/issues/699

**Comment by ben-eb** [comment]
Fixed in the latest release of `colormin` and `postcss-colormin`. Pass the `legacy` option to enable this fix; e.g:

```js
{
  colormin: {legacy: true}
}
```

**Comment by librisius** [comment]
Thanks @ben-eb :smile:
