### ISSUE TITLE
Setting options in gulp-cssnano

### ISSUE THREAD

**Issue by jerome-nelson** [ben-eb/gulp-cssnano#43]
Hi @ben-eb, I'm attempting to use gulp-cssnano on node v0.10.36. I've managed to get the plugin integrapted into a `testing` gulp task but how do I set options?

Looking at the documentation for various plugins + the source of cssnano [vanilla ver. not gulp] I can see the options allowed and where they are taken from, as well as also having the `disable: true` attribute set to ignore an option.

The problem is I'm attempting to add them to my gulpfile and it's a no go.

```
 return gulp.src('bingotest/*.css')
            .pipe(p.plumber())
            .pipe(p.cssnano(
                autoprefixer: false,
                disableDuplicates: {disabled: true}
             ))
            .pipe(p.rename('test.css'))
            .pipe(gulp.dest('test/'));
```

I have also tried using gulp-cssnano and nano (as I'm using gulp-load-plugins all plugins are loaded async. into the p function.

**Comment by ben-eb** [comment]
You missed the enclosing object literal. :wink:

```js
 return gulp.src('bingotest/*.css')
            .pipe(p.plumber())
            .pipe(p.cssnano({
                autoprefixer: false,
                disableDuplicates: {disabled: true}
             }))
            .pipe(p.rename('test.css'))
            .pipe(gulp.dest('test/'));
```

**Comment by jerome-nelson** [comment]
Thanks for the quick reply!

Sorry I messed the code sample up - here is the amended ver (it's still not working).

```
gulp.src(siteLessDir + 'build.less')
        .pipe(p.plumber())
        .pipe(p.less())
        .pipe(p.rename(siteName + '.css'))
        .pipe(p.cssnano({
            autoprefixer: { browsers: ['last 2 versions'] },
            discardDuplicates: {disabled: true}
        }))
        .pipe(gulp.dest(siteDir + '/css'));
```
```

a {
  display: flex;
}


a {
  display: flex;
}
```

I'm using the above two codes to test both autoprefixer and discardDuplicates, but no dice.

I get  `a { display:flex;}` only once and with no prefixes. Any further ideas as to what this could be?

**Comment by ben-eb** [comment]
Yep; Autoprefixer is used in a removal only capacity as this is a compression tool. You can add prefixes if you set `add` to true; `{autoprefixer: {add: true}}`. I expect that the second rule is removed because postcss-merge-rules takes care of merging those two rules together.

**Comment by jerome-nelson** [comment]
Thanks again!!!!! I can now see the autoprefixer changes (upon looking into cssnano's index.js I can see the option as well). 

However `mergeRules: {disable: true}` isn't working. Can I clarify how do I find the options for gulp-cssnano - I assumed it was the `processors` obj. literal in index.js with the _postcss part removed and the first letter lowercased.

**Comment by ben-eb** [comment]
There's a list on http://cssnano.co/options/. :smile:

**Comment by jerome-nelson** [comment]
Thanks again. I have read that page and http://cssnano.co/optimisations/ but the problem is I don't understand what the default option is to install an option outside of the `var defaultOptions` and `var safeOptions`.

`postcss_MergeRules` = mergeRules but then how can I tell if it is on?

**Comment by ben-eb** [comment]
If you pass `{disable: true}` or `false` to any plugin, it will disable it;

```js
{
  mergeRules: {disable: true}
}
```

Is equivalent to:

```js
{
  mergeRules: false
}
```

The `postcss` prefix is entirely optional (for readability only). So this config is also the same as the prior two:

```js
{
  postcssMergeRules: false
}
```

All *modules* are loaded by default, but they have different settings depending on whether `safe` mode is on or not. The problem you might be facing is overlapping functionality; some of the modules naturally do the same things depending on the CSS passed. So in this case you would want to disable `mergeRules` & `discardDuplicates` to ensure that the second rule exists (I don't recommend this for obvious compression reasons though).

**Comment by jerome-nelson** [comment]
Thanks @ben-eb  for the help. This helps me understand cssnano much better.
