### ISSUE TITLE
URL normalize removes "www." inside background url

### ISSUE THREAD

**Issue by gerbsen** [ben-eb/gulp-cssnano#44]
Hey,
I'm using cssnano via Gulp/Jhipster. I just saw that the normalizeUrl processor break my links. :/ I tried to disable it but I couldn't figure out the notation:

    cssnano = require('gulp-cssnano'),
    gulp.task('usemin', ['images', 'sass'], function() {
        return gulp.src([config.app + '**/*.html', '!' + config.app + '@(dist|bower_components)/**/*.html'])
            .pipe(plumber({errorHandler: handleErrors}))
            .pipe(usemin({
                css: [
                    prefix,
                    'concat',
                    cssnano,
                    rev
                ],
                html: [
                    htmlmin.bind(htmlmin, {collapseWhitespace: true})
                ],
                js: [
                    sourcemaps.init,
                    ngAnnotate,
                    'concat',
                    uglify.bind(uglify, { mangle: false }),
                    rev,
                    sourcemaps.write.bind(sourcemaps.write, '.')
                ]
            }))
            .pipe(gulp.dest(config.dist));
    });

Why would cssnano remove the 'www', isn't this very dangerous?
Cheers,
Daniel

**Comment by ben-eb** [comment]
> **Removing or adding “www” as the first domain label**. Some websites operate identically in two Internet domains: one whose least significant label is “www” and another whose name is the result of omitting the least significant label from the name of the first, the latter being known as a naked domain. For example, `http://example.com/` and `http://www.example.com/` may access the same website. Many websites redirect the user from the www to the non-www address or vice versa. A normalizer may determine if one of these URLs redirects to the other and normalize all URLs appropriately. Example:
`http://www.example.com/` → `http://example.com/`

https://en.wikipedia.org/wiki/URL_normalization

The option can be turned off with this configuration:

```js
cssnano({
  normalizeUrl: {
    stripWWW: false
  }
})
```

**Comment by titoBouzout** [comment]
Can you please let me know how to turn this off on the command line?

**Comment by ben-eb** [comment]
@titoBouzout

```sh
$ cssnano --no-normalizeUrl.stripWWW
```

**Comment by titoBouzout** [comment]
Thanks for the additional information! Im using postcss so for me looks like this:

> postcss --use cssnano --no-cssnano.normalizeUrl  

I believe stripWWW is dangerous setting, and should not be default in my opinion..... most site set up complete redirects to add or remove the WWW and also some sites are different on both locations. normalizing is fine, but removing or adding a www. is not the same thing...

**Comment by ben-eb** [comment]
@titoBouzout I've added `stripWWW` to cssnano's safe mode now.
