### ISSUE TITLE
still zindex, but could you please explain how to config and disable the feature

### ISSUE THREAD

**Issue by ericlormul** [ben-eb/gulp-cssnano#46]
I'm using mgechev's angular2 seed, https://github.com/mgechev/angular2-seed
Thanks so much.

**Comment by heliomsolivas** [comment]
did you added z-index:false?

**Comment by ericlormul** [comment]
Hi heliomsolivas,

Thanks so much for replying. I'm such a noob for gulp and npm, and I'm using angular2 seed. Could you please specify where to add z-index: false? I really appreciate it. Thanks in advance.

**Comment by heliomsolivas** [comment]
sure, no problem, assuming that you have a gulpfile, in your task use cssnano like this 

```
.pipe(cssnano({
            zindex:false
        }))
```

**Comment by bonejon** [comment]
Hi,

I am also using the angular2-seed project and am wishing to disable the zindex processing. 

I have located the configuration of cssnano in /tools/tasks/seed/build.html_css.ts, modifying the code to the following, does not seem to work.

`processors.push(
    cssnano({
      discardComments: {removeAll: true},
      zindex: false
    })
  );
`

`Argument of type '{ zindex: boolean; }' is not assignable to parameter of type 'IOptions'. Object literal may only specify known properties, and 'zindex' does not exist in type 'IOptions'.
(property) zindex: boolean`

The build is pure typescript, and is using "cssnano": "^3.5.2". I would appreciate any help you could give.

**Comment by bonejon** [comment]
@ericlormul Im not sure if you managed to get this working, but the solution is as follows:

edit: /tools/manual_typings/seed/cssnano.d.ts and change IOptions to be:
`  interface IOptions {
    discardComments: {
      removeAll: boolean;
    },
    zindex: boolean;
  }`

then then edit /tools/tasks/seed/build.html_css.ts, about line 18 change the cssnano config to be:
`    cssnano({
      discardComments: {removeAll: true},
      zindex: false
    })`

And you should be good to go.

Hope this help.

**Comment by ericlormul** [comment]
@bonejon 
Thanks for taking a look at the structure of angular2-seed project and point out this out. It's working right now.

**Comment by ben-eb** [comment]
Going to mark this as resolved, thanks guys. 👍

**Comment by 1izpena** [comment]
Hi, in my case 
` .pipe($.cssnano({discardUnused: {fontFace: false},zindex: false}))`
<p>Not working.
<p>My mimify CSS appears z-index:1, while in my normal CSS appears z-index:1000000
<p>What is the problem??

**Comment by ben-eb** [comment]
@1izpena This config looks fine to me, would you be able to provide a minimal repository that reproduces?
