### ISSUE TITLE
@font-face stripped

### ISSUE THREAD

**Issue by rafis** [ben-eb/gulp-cssnano#49]
app.css:

    /*!
     *  Font Awesome 4.6.3 by @davegandy - http://fontawesome.io - @fontawesome
     *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
     */
    /* FONT PATH
     * -------------------------- */
    @font-face {
      font-family: 'FontAwesome';
      src: url("../fonts/fontawesome-webfont.eot?v=4.6.3");
      src: url("../fonts/fontawesome-webfont.eot?#iefix&v=4.6.3") format("embedded-opentype"), url("../fonts/fontawesome-webfont.woff2?v=4.6.3") format("woff2"), url("../fonts/fontawesome-webfont.woff?v=4.6.3") format("woff"), url("../fonts/fontawesome-webfont.ttf?v=4.6.3") format("truetype"), url("../fonts/fontawesome-webfont.svg?v=4.6.3#fontawesomeregular") format("svg");
      font-weight: normal;
      font-style: normal; }

    .fa {
      display: inline-block;
    }

gulpfile.js:

    var gulp = require('gulp'),
        cssnano = require('gulp-cssnano');

    gulp.task('default', function() {
        return gulp
            .src('app.css')
            .pipe(cssnano({ minifyFontValues: false }))
            .pipe(gulp.dest(''));
    });

result:

    /*!
     *  Font Awesome 4.6.3 by @davegandy - http://fontawesome.io - @fontawesome
     *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
     */.fa{display:inline-block}

Why `@font-face` getting stripped?

**Comment by dakanji** [comment]
Same issue. Have multiple font faces in a file and one of them always gets stripped.

**Comment by ben-eb** [comment]
It's not `minifyFontValues` that is responsible for this transform. https://github.com/ben-eb/postcss-discard-unused#fontface

```js
var gulp = require('gulp'),
    cssnano = require('gulp-cssnano');

gulp.task('default', function() {
    return gulp
        .src('app.css')
        .pipe(cssnano({ minifyFontValues: false, discardUnused: false }))
        .pipe(gulp.dest(''));
});
```

**Comment by dakanji** [comment]
A bit lost but basically running without arguments:

```
var gulp = require('gulp'),
    cssnano = require('gulp-cssnano');

gulp.task('default', function() {
    return gulp
        .src('app.css')
        .pipe(cssnano())
        .pipe(gulp.dest(''));
});

```

After this, one and only one, font face item out of four in app.css just doesn't appear.
Seems to be a recent issue. I am fairly sure this did not happen last week.

**Comment by rafis** [comment]
Hmm, good, but I've already switched to `gulp-clean-css`. What is better PostCSS or CleanCSS?

**Comment by caub** [comment]
@rafis https://caub.github.io/css-min-bench
