### ISSUE TITLE
minified output to *.min.css

### ISSUE THREAD

**Issue by Jogai** [ben-eb/gulp-cssnano#5]
I have the following gulp task to generate a css & map file from my less input. This works fine, but I like to have a separate App.min.css file as the output of cssnano. How can I achieve that?

    gulp.task('less', function () {
        var postcss = require('gulp-postcss');
        var cssnext = require('gulp-cssnext');
        var cssnano = require('gulp-cssnano');
        var processors = [        
            cssnext
        ];
        return gulp.src('App.less')
            .pipe(sourcemaps.init())
            .pipe(less({
                paths: [path.join(__dirname, 'less', 'includes', "bower_components")]
            }))
            .pipe(postcss(processors))
            .pipe(cssnano({discardComments: { removeAll: true } }))
            .pipe(sourcemaps.write('.'))
            .pipe(gulp.dest(''));
    });

**Comment by ben-eb** [comment]
```js
var merge = require('merge-stream');
var rename = require('gulp-rename');
var clone = require('gulp-clone');
var gulp = require('gulp');
var sourcemaps = require('gulp-sourcemaps');

gulp.task('less', function () {
    var postcss = require('gulp-postcss');
    var cssnext = require('cssnext');
    var cssnano = require('gulp-cssnano');
    var processors = [
        cssnext
    ];

    var css = gulp.src('App.less')
      .pipe(sourcemaps.init())
      .pipe(less({
          paths: [path.join(__dirname, 'less', 'includes', "bower_components")]
      }))
      .pipe(postcss(processors));

    var min = css.pipe(clone())
      .pipe(cssnano({discardComments: {removeAll: true}}))
      .pipe(rename('app.min.css'));

    return merge(css, min)
      .pipe(sourcemaps.write('.'))
      .pipe(gulp.dest(''));
});
```

Works for me.

**Comment by Jogai** [comment]
Thanks a lot!
