### ISSUE TITLE
Source maps aren't correctly generated

### ISSUE THREAD

**Issue by timkraut** [ben-eb/gulp-cssnano#50]
Hi guys,

I've got an issue with gulp-cssnano (2.1.2) and gulp-sourcemaps (1.6.0) in gulp 3.9.1: The generated source maps don't work in the browser. 

```javascript
gulp.task('css', function() {
    return gulp.src('...', {base: '.'})
               ...
               .pipe(sourcemaps.init())
                   .pipe(sass())
                   //.pipe(autoprefixer(...)) // <-- Causes source maps not to work anylonger
                   .pipe(cssnano()) // <-- Causes source maps not to work anylonger
               .pipe(sourcemaps.write())
               ...
               .pipe(gulp.dest('...'))
               .pipe(browserSync.stream())
        ;
});
```

By commenting out every line and trying to find the plugin which causes the issue, I found that 2 plugins cause the source maps to stop working: gulp-autoprefixer and gulp-cssnano. Currently, there is an open issue for gulp-autoprefixer which might be related to this one: https://github.com/sindresorhus/gulp-autoprefixer/issues/55. The issues seems to be related to consuming existing source maps.

**Comment by ben-eb** [comment]
Hi Tim,

Does it work with gulp-postcss? https://github.com/ben-eb/gulp-cssnano/issues/16#issuecomment-170343294

**Comment by timkraut** [comment]
@ben-eb Sry for not coming back to you earlier. Using gulp-postcss and cssnano works fine for me.
