### ISSUE TITLE
No mac address - uniqid() falls back to uniqid.process()

### ISSUE THREAD

**Issue by zietbukuel** [ben-eb/gulp-cssnano#51]
I'm getting this error using this gulp plugin. I'm using the latest version available.

Info: No mac address - uniqid() falls back to uniqid.process(). { [Error: Command failed: cat: /sys/class/net/eth0/address: Permission denied
] killed: false, code: 1, signal: null }

**Comment by ben-eb** [comment]
Hello,

I think this message is inconsequential for you, as it is printed when the machine does not have a MAC address. I'm not sure that it is the best developer experience to print this information however, I would much prefer for this to happen silently.

ping @adamhalasz

**Comment by ben-eb** [comment]
Migrating this issue to https://github.com/bayorigin/uniqid/issues/7, please subscribe there for updates. 😄
