### ISSUE TITLE
Cssnano renames animation name resulting in unexpected animation

### ISSUE THREAD

**Issue by ssurve** [ben-eb/gulp-cssnano#52]
I have this in my CSS file:
.blinking-cursor {
    animation: blinker 1s linear infinite;
}

@keyframes blinker {
    10% {
        opacity: 1
    }
    45% {
        opacity: 0
    }
    55% {
        opacity: 0
    }
    90% {
        opacity: 1
    }
}
--------
cssnano changes "blinker" to "a" and this causes the cursor to start spinning (intended animation: blinking).

Using ---> "gulp-cssnano": "^2.1.2"

**Comment by StephenTG** [comment]
I think I'm actually having pretty much the exact same problem. We've got two separate minified css files, and the minification changes the keyframe names to a, b, c, etc in both, so there's a name collision and some of the animations get messed up. Is there a no-mangle option somewhere?

**Comment by matitalatina** [comment]
Just call cssnano in this way:

```
cssnano({
  reduceIdents: false
})
```

[Here the documentation](http://cssnano.co/optimisations/reduceIdents).
