### ISSUE TITLE
This plugin is BLACKLISTED & does not seem to handle multiple files correctly

### ISSUE THREAD

**Issue by Stijnkool** [ben-eb/gulp-cssnano#55]
This plugin does not seem to handle multiple files in a stream correctly.
When you pass options to the plugin ex. `{safe: true}` this is only used for the first file in the stream. The other files receive `{safe: null}` for some reason.

<img width="410" alt="screen shot 2016-09-02 at 15 17 56" src="https://cloud.githubusercontent.com/assets/2602506/18205143/b537d7ee-7120-11e6-9d4c-0c500e3d6613.png">

From **blackList.json** at gulp repo:

<img width="444" alt="screen shot 2016-09-02 at 15 21 13" src="https://cloud.githubusercontent.com/assets/2602506/18205190/f5ab7768-7120-11e6-9ef8-71ba1d1b50f9.png">

**Comment by ben-eb** [comment]
Hi Stijjn;

* For some further information about gulp-cssnano being blacklisted, see https://github.com/gulpjs/plugins/issues/210#issuecomment-193522601.
* The `safe` option propagation is a known bug, here's an issue tracking this: https://github.com/ben-eb/cssnano/issues/268.
