### ISSUE TITLE
Passing autoprefixer browsers array

### ISSUE THREAD

**Issue by pawelcreare** [ben-eb/gulp-cssnano#6]
Hello. Sorry for newbie but Im not sure If I understand  it right.
Is cssnano comes bundled with all these plugins line autoprefixer?
If yes, how can I pass a browsers list into cssnano?

```
gulp.task('styles', function() {
    return gulp.src('./src/style.css')
        .pipe(nano({
            browsers: ['> 1%', 'last 2 versions', 'Firefox >= 20']
        }))
        .pipe(gulp.dest('./dist'));
});
```

Please help me to set that up correctly.

**Comment by ben-eb** [comment]
I'm considering moving the `browsers` option to the main options object, but for now you can do:

```js
gulp.task('styles', function() {
    return gulp.src('./src/style.css')
        .pipe(nano({
            autoprefixer: {browsers: ['> 1%', 'last 2 versions', 'Firefox >= 20']}
        }))
        .pipe(gulp.dest('./dist'));
});
```

**Comment by pawelcreare** [comment]
It doesn't work for me. These are my settings. It doesn't seem to be adding any prefixes automaticlly.

```javascript
var gulp = require('gulp');
var nano = require('gulp-cssnano');

gulp.task('default', function() {
  return gulp.src('./main.css')
    .pipe(nano({
      autoprefixer: { browsers: ['> 1%', 'last 2 versions', 'Firefox >= 20'] }
    }))
    .pipe(gulp.dest('./out'));
});
```

Input CSS
```css
.box {
  box-sizing: border-box;
}
```

Output
```css
.box{box-sizing:border-box}
```

**Comment by ben-eb** [comment]
Ah right. By default, autoprefixer is just used to *remove* prefixes as this is a compression tool. You can override this if you wish by:

```js
gulp.task('default', function() {
  return gulp.src('./main.css')
    .pipe(nano({
      autoprefixer: {browsers: ['> 1%', 'last 2 versions', 'Firefox >= 20'], add: true}
    }))
    .pipe(gulp.dest('./out'));
});
```

**Comment by pawelcreare** [comment]
That worked for me.

I know it is compression tool (amazing one) but that makes sense for me to sort out all prefixes mess via one single task, instead of creating separated autoprefixing pipe above.

Thank you a lot!!!

**Comment by ben-eb** [comment]
No problem. :smile:

**Comment by razvanpavel** [comment]
Thank you! This was gold!
