### ISSUE TITLE
weird px conversion

### ISSUE THREAD

**Issue by apansky** [ben-eb/gulp-cssnano#7]
not sure if im only one but, my px sizes end up being weird values ... like "1pc" etc. After removing cssnano task from gulp it works..

Anyone ?
thanx !

**Comment by ben-eb** [comment]
It's off by default since cssnano 3.2.0. :smile:

https://github.com/ben-eb/cssnano/issues/67

**Comment by apansky** [comment]
ok, im now officialy stupid, sorry and thanx :D
