### ISSUE TITLE
update npm packages?

### ISSUE THREAD

**Issue by tayvano** [ben-eb/gulp-cssnano#74]
https://www.npmjs.com/package/gulp-cssnano is extremely out of date and the updates to cssnano speed + options have been pretty significant. can we get an update on npm so repos that aren't on postcss can be happy too?

**Comment by ben-eb** [comment]
@tayvano Due to the caret in our dependencies, we're good for each *minor* & *patch* version of cssnano right up until v4 is released. A fresh install will pull down `3.8.0` as of this writing, no need for another release yet. 😄

**Comment by tayvano** [comment]
Weird. I'll take a closer look at what versions are where on my end. A bug was supposedly fixed and I assumed I must not have had the latest version as I was still encountering the bug. 

Thanks for the info & sorry for troubling you. Have a good one.
