### ISSUE TITLE
counter variables rewritten

### ISSUE THREAD

**Issue by websmiths** [ben-eb/gulp-cssnano#77]
Hi, I've just had to disable cssnano because it rewrites (minifies) my counter variable names, which are obviously still referenced in the html – so the counters break.
A quick search hasn't helped me find an option for avoiding this. 
Any ideas?
Cheers,
Julian

**Comment by ben-eb** [comment]
Hi @websmiths,

I'm curious as to how these identifiers are used; could you show me an example of their usage in HTML please?

You can disable this option with `{reduceIdents: false}`, or the `counter` transform specifically with `{reduceIdents: {counterStyle: false}}`

https://github.com/ben-eb/postcss-reduce-idents#counterstyle

**Comment by websmiths** [comment]
Hi @ben-eb,

Firstly, many thanks for the tip. I figured it could (should) be possible, but I didn’t find the setting via the cssnano site. I’ll have a play when I get back to work next week.

As to how I’m using it: in order to get a bit of extra control over the display of lists, I’ve applied a counter variable (called `level`) to an `li:before` selector `content` property. Essentially turning off the auto-numbering and replacing it with the counter. It's a bit fiddly and not über efficient, but we’re going for a particular effect.

This breaks the `start` attribute (which was deprecated, then reinstated), used to start a list from a particular number. In order to facilitate continuing lists we use a `style` tag in the html to reset the counter to a particular index.

Thus, when the minifier changes the variable name (from `level` to `a`) in the stylesheet, the link with the html (which still references `level`) breaks.

Hope this makes sense. Example code follows.
Thanks again

CSS:
```css
ol {
    counter-reset: level; 
    list-style-type: none;
}
ol > li {
    position: relative;
    counter-increment: level; 
}
ol > li:before {
    content: counter(level) "."; 
    etc.
}
```

HTML - to start a list at number 4 (index 3):
```html
<ol style="counter-reset: level 3;">
      <li>Fourth item</li>
      <li>Fifth item …</li>
</ol>
```

**Comment by ben-eb** [comment]
@websmiths Brilliant, thanks for the detailed explanation. 😄
