### ISSUE TITLE
This plugin change z-index!

### ISSUE THREAD

**Issue by librisius** [ben-eb/gulp-cssnano#8]
I didn't see that You mentioned it, but it's really important!

**Comment by ben-eb** [comment]
Thanks for the feedback; I'm planning on turning this off by default for v4. https://github.com/ben-eb/cssnano/issues/88

For now you can pass `{zindex: false}` to disable. :smile:

**Comment by pelizza** [comment]
Hey,

There are other CSS properties affected? I really like gulp-cssnano, but I don't want it to change my CSS properties... :)

**Comment by ben-eb** [comment]
@pelizza Is it related to this issue? Pass `{zindex: false}` to turn this off.

Generally speaking a minifier is supposed to affect CSS properties, by converting values/properties to shorter representations. We don't just remove whitespace. :smile:

**Comment by pelizza** [comment]
Hi @ben-eb,

Yes it is. And the `{zindex: false}` resolved the problem here :)

And, yes you are right. It is supposed to affect CSS properties. I just don't expect it to change values, like this z-index case, for example. Maybe am I looking it on the wrong way?

BTW, contrats and thanks for this tool! It is really awesome!

**Comment by ben-eb** [comment]
@pelizza Have a look at the linked issue; the idea for the optimisation was based on Bootstrap's larger-than-necessary `z-index` values. But with the benefit of hindsight I learned that this transform assumes a lot from the user for not much gain. It can make sense in some specific cases but we will leave this choice up to the user, starting from version 4.

**Comment by pelizza** [comment]
That's great @ben-eb, it totally makes sense.

Just to explain my case here, as my application runs as a plugin, it is embedded into another app which I can have control over the CSS. So, sometimes I have to set some CSS properties to fit right on the screen together with the host app.

Thanks for your attention!

**Comment by sponnuru-nisum-com** [comment]
we need to give like this  if you use usemin
.pipe(usemin({
            css: [
                prefix,
                'concat',
                function () {return cssnano({ zindex: false });},

**Comment by miltonhowe** [comment]
This created a frustrating problem for me using angular-toastr with bootstrap. After some hours of digging I eventually identified the culprit. The option is labelled as unsafe in the documentation. That seems an indication to me that it should be off by default.

**Comment by ben-eb** [comment]
@miltonhowe See https://github.com/ben-eb/cssnano/issues/88.

**Comment by zietbukuel** [comment]
This only works the first time gulp executes cssnano, if we use "watch" then whenever cssnano is called after the first execution, it will ignore {zindex:false}

**Comment by ben-eb** [comment]
@zietbukuel `watch` from where exactly?

**Comment by zietbukuel** [comment]
@ben-eb 

Example:

```javascript
gulp.task('watch', function () {
   gulp.watch('scss/style.scss', ['sass']);
});
```

**Comment by 1izpena** [comment]
Hi, I put:
<p>
`.pipe($.cssnano({discardUnused: {fontFace: false}},{ zindex: false }))`
But It not work.
<p>In the mimify CSS appears z-index:1, but in the normal CSS I put z-index:10000000.
<p>What is the problem?

**Comment by williambryan777** [comment]
thanks so much ,the cssnano change the z-index make me very confused this morning,so here i found answer.this is is my webpack.config.js:
```
 postcss: function() {
        return [autoprefixer, precss, new cssnano({ zindex: false })];
    },
```

**Comment by Clarence-pan** [comment]
I was really surprised...

**Comment by LucaPrete** [comment]
Hello, I use gulp-cssnano 2.1.2 and cssnano 3.10.0. By default this is still not disabled. I don't understand where this {z-index: false} directive should go. The only place where I see cssnano called is in a gulp task:
```
....
.pipe(cssnano())
...
```

that I've tried to transform in
```
....
.pipe(cssnano({zindex: false}))
....
```

unfortunately without results.

Any help is greatly appreciated!

Thanks,

-Luca

**Comment by mithlesh-kumar** [comment]
Pass {z-index: false} as param in cssnano.
`...
.pipe(cssnano({z-index: false}))
....`

**Comment by LucaPrete** [comment]
@mithlesh-kumar unfortunately this didn't make the trick.

First I've tried as you suggested
`.pipe(cssnano({z-index: false}))`

but this generates a syntax error and I can't even start the build.

Then, I tried

`.pipe(cssnano({'z-index': false}))`

While this solved the syntax issue, did have any effect, just as when I was using
`.pipe(cssnano({zindex: false}))`

**Comment by sgnl** [comment]
I got caught by this today. `{zindex: false}` is sort of helpful...

for user who might be using postcss with a `postcss.config.js` file, this is how I'm using it:

```
module.exports = (ctx) => ({
  parser: 'postcss-scss',
  plugins: {
    'precss': {},
    'autoprefixer': {
      browsers: ['> 1% in US', 'last 3 versions']
    },
    'cssnano': ctx.env === 'production' ? {zindex: false} : false // <-- 👀 
  }
});
```

**Comment by tanoabeleyra** [comment]
It took me couple minutes to understand why z-index values were fine on development but not on production.
`{zindex: false}` worked, but IMO it should be disabled by default.

**Comment by PUncle** [comment]
@LucaPrete I had the same issue.

`.pipe(cssnano({ zindex: false }))` is correct, but i had to do a `gulp clean` and then rebuild for it to take effect.

**Comment by paulius005** [comment]
`zindex: false` isn't working in `3.10.0`

I just switched to https://github.com/NMFR/optimize-css-assets-webpack-plugin until this is all figured out in a stable version of v4

**Comment by cdeutsch** [comment]
`zindex: false` should be the default.

This was a colossal waste of time to try figure out.
