### ISSUE TITLE
Cssnano deletes the comments. How to keep them?

### ISSUE THREAD

**Issue by Alecto** [ben-eb/gulp-cssnano#87]
I need special comments for WordPress themes, but I can not find a description of the options for cssnano  to understand how to disable deleting comments.

**Comment by ben-eb** [comment]
Sure, bear in mind it's different if you're using the release candidates.

3.x options:

```js
{
  discardComments: false,
};
```

4.x options:

```js
{
  preset: ['default', {discardComments: false}],
}
```

Note that any comments that begin with `!` are kept by default.
