### ISSUE TITLE
supplying autoprefixer browsers

### ISSUE THREAD

**Issue by af-bergstrom** [ben-eb/gulp-cssnano#9]
trying to get some autoprefixer options passed along but I can't seem to get it working:

```
var myBrowsers = [
	'last 2 versions',
	'safari >= 8',
	'ie >= 10',
	'ff >= 20',
	'ios 6',
	'android 4'
]
var cssNanoProps = {
	zindex: true,
	autoprefixer: {
		browsers: myBrowsers
	}
};
```
I've tried: 
```
.pipe($.cssnano(cssNanoProps))
```
aswell as:
```
.pipe($.cssnano({
    	autoprefixer: {browsers: myBrowsers}
}))
```
and:
```
.pipe($.cssnano({
    	autoprefixer: {
            browsers: [
	        'last 2 versions',
	        'safari >= 8',
	        'ie >= 10',
	        'ff >= 20',
	        'ios 6',
	        'android 4'
           ]
      }
}))
```
Any guidance would be appreciated :)

**Comment by ben-eb** [comment]
What isn't working about this? Does https://github.com/ben-eb/gulp-cssnano/issues/6 solve your issue?

**Comment by af-bergstrom** [comment]
Thanks for the fast response, that solved it for me! When I've previously used autoprefixer I haven't needed to add the option add:true but it makes sense :)

**Comment by ben-eb** [comment]
No problem. :+1:
