### ISSUE TITLE
gulp-util is deprecated

### ISSUE THREAD

**Issue by tomascassidy** [ben-eb/gulp-cssnano#92]
gulp-util has been deprecated so the dependency for gulp-cssnano should be updated to plugin-error.

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by tomascassidy** [comment]
I made a basic attempt at a pull request in #93, but clearly don't know enough about NPM to fix the test cases properly.

**Comment by demurgos** [comment]
Why did you close your PR? Do you want me to pick this up?

**Comment by tomascassidy** [comment]
I've re-opened it again.  The change to index.js is simply just changing gulp-util to plugin-error.  I ran into issues trying to change gulp-util in test.js that I'm not sure how to fix properly.

**Comment by demurgos** [comment]
Thanks, I am looking into it but it is not obvious. I'll probably send another PR if I find the issue.

**Comment by demurgos** [comment]
It looks like a Vinyl issue (either documentation or implementation), I reported it [there](https://github.com/gulpjs/vinyl/issues/140).

**Comment by muser83** [comment]
When will the issue resolved? Are you having problems?
Thank you
